Web/src/Entity/Community.php
<?php

namespace App\Entity;

use App\Repository\CommunityRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommunityRepository", repositoryClass=CommunityRepository::class)
 */
class Community
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $grp_name;

    /**
     * @ORM\Column(type="string", length=255)
     *  @Assert\NotBlank
     *  @Assert\Email(
     *     message = "The email '{{ value }}' is not a valid email.",
     *     checkMX = true
     * )
     */
    private $email;

    /**
     * @ORM\Column(type="integer" , length=8)
     * @Assert\NotBlank(message="champ obligatoire")
     *@Assert\Length(min = 8, max = 10, minMessage = "min_lenght", maxMessage = "max_lenght")
     *@Assert\Regex(pattern="/^[0-9]*$/", message="number_only")
     */
    private $phone;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="champ obligatoire")
     * @Assert\Length(
     *      min = 5,
     *      minMessage = "Your description must be at least {{ limit }} characters long",

     * )
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity=Blog::class, mappedBy="community")
     * @ORM\JoinColumn(nullable=false)
     */
    private $blogs;

    public function __construct()
    {
        $this->blogs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getGrpName(): ?string
    {
        return $this->grp_name;
    }

    public function setGrpName(string $grp_name): self
    {
        $this->grp_name = $grp_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?float
    {
        return $this->phone;
    }

    public function setPhone(float $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|Blog[]
     */
    public function getBlogs(): Collection
    {
        return $this->blogs;
    }

    public function addBlog(Blog $blog): self
    {
        if (!$this->blogs->contains($blog)) {
            $this->blogs[] = $blog;
            $blog->setCommunity($this);
        }

        return $this;
    }

    public function removeBlog(Blog $blog): self
    {
        if ($this->blogs->removeElement($blog)) {
            // set the owning side to null (unless already changed)
            if ($blog->getCommunity() === $this) {
                $blog->setCommunity(null);
            }
        }

        return $this;
    }
}

Web/src/Form/CommunityType.php
<?php

namespace App\Form;

use App\Entity\Community;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommunityType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('grp_name')
            ->add('email')
            ->add('phone')
            ->add('description')
            ->add ('save',SubmitType::class, ['attr' => ['formnovalidate' => 'formnovalidate']])

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Community::class,
        ]);
    }
}

Web/src/Controller/CommunityController.php
<?php

namespace App\Controller;

use App\Entity\Community;
use App\Form\CommunityType;
use App\Repository\CommunityRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/community")
 */
class CommunityController extends AbstractController
{
    /**
     * @Route("/", name="community_index", methods={"GET"})
     */
    public function index(CommunityRepository $communityRepository): Response
    {
        return $this->render('community/index.html.twig', [
            'communities' => $communityRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="community_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $community = new Community();
        $form = $this->createForm(CommunityType::class, $community);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($community);
            $entityManager->flush();

            return $this->redirectToRoute('community_index');
        }

        return $this->render('community/new.html.twig', [
            'community' => $community,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="community_show", methods={"GET"})
     */
    public function show(Community $community): Response
    {
        return $this->render('community/show.html.twig', [
            'community' => $community,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="community_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Community $community): Response
    {
        $form = $this->createForm(CommunityType::class, $community);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('community_index');
        }

        return $this->render('community/edit.html.twig', [
            'community' => $community,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="community_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Community $community): Response
    {
        if ($this->isCsrfTokenValid('delete'.$community->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($community);
            $entityManager->flush();
        }

        return $this->redirectToRoute('community_index');
    }
}

Web/templates/community/_delete_form.html.twig
<form method="post" action="{{ path('community_delete', {'id': community.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ community.id) }}">
    <button class="btn btn-danger" href="#"> Delete <a class="fa fa-trash-o "> </a> </button>
</form>

Web/templates/community/_form.html.twig
{{ form_start(form) }}


<div class="card" xmlns="http://www.w3.org/1999/html">
    <div class="card-body">
        <div class="card-title">Create New Community</div>
        <hr>

        <div class="form-group">
            <label for="input-6">Group Name</label>

            {{ form_widget(form.grp_name ,{'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.grp_name) }}</div>
        <div class="form-group">
            <label for="input-9">Email </label>

            {{ form_widget(form.email ,{'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.email) }}</div>
        <div class="form-group">
            <label for="input-8">Description</label>

            {{ form_widget(form.description ,{'attr': {'class': 'form-control'}}) }}
        {{ form_errors(form.description) }}</div>
        <div class="form-group">
            <label for="input-7">Phone <i class="fa fa-phone "  > </i></label>

            {{ form_widget(form.phone ,{'attr': {'class': 'form-control'}}) }}
            {{ form_errors(form.phone) }}
        </div>
            <div class="form-group py-2">
                <div class="icheck-material-white">
                    <input type="checkbox" id="user-checkbox2" checked=""/>
                    <label for="user-checkbox2">I Agree Terms & Conditions</label>
                </div>
            </div>
            <div class="form-group">
                <i class="icon-lock"> </i>
                    {{ form_widget(form.save ,{'attr': {'class': 'btn btn-light btn-round px-5'}} ) }}

            </div>

        </div>
    </div>

    {{ form_end(form) }}

Web/templates/community/edit.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}Edit Community{% endblock %}

{% block content %}
    <h1>Edit Community</h1>

    {{ include('community/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('community_index') }}">  <i class="fa fa-long-arrow-left" > </i>back to list</a>

    {{ include('community/_delete_form.html.twig') }}
{% endblock %}

Web/templates/community/index.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}Community index{% endblock %}

{% block content %}
    <h1>Community index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Grp_name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Description</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for community in communities %}
            <tr>
                <td>{{ community.id }}</td>
                <td>{{ community.grpName }}</td>
                <td>{{ community.email }}</td>
                <td>{{ community.phone }}</td>
                <td>{{ community.description }}</td>
                <td>
                    <a href="{{ path('community_show', {'id': community.id}) }}">Show</a>
                    <a href="{{ path('community_edit', {'id': community.id}) }}">Edit</a>
                    <a href="{{ path('community_delete', {'id': community.id}) }}">Delete</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('community_new') }}">Create new Community</a>
{% endblock %}

Web/templates/community/new.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}New Community{% endblock %}

{% block content %}


    {{ include('community/_form.html.twig') }}

    <a href="{{ path('community_index') }}">  <i class="fa fa-long-arrow-left" > </i>back to list</a>
{% endblock %}

Web/templates/community/show.html.twig
{% extends 'baseBack.html.twig' %}

{% block title %}Community{% endblock %}

{% block content %}
    <h1>Community</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ community.id }}</td>
            </tr>
            <tr>
                <th>Grp_name</th>
                <td>{{ community.grpName }}</td>
            </tr>
            <tr>
                <th>Email  </th>
                <td>{{ community.email }}</td>
            </tr>
            <tr>
                <th>Phone  <i class="fa fa-phone "  > </i></th>
                <td>{{ community.phone }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ community.description }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('community_index') }}">  <i class="fa fa-long-arrow-left" > </i> Back to list</a>

    <a href="{{ path('community_edit', {'id': community.id}) }}">Edit</a>

    {{ include('community/_delete_form.html.twig') }}
{% endblock %}